config/routes.rb
Mizzouacm::Application.routes.draw do

  resources :groups


  resources :attachments


  resources :posts


  resources :projects


  resources :events


  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ] do
    resources :skills, :only => [:create, :destroy]
  end
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
  match '/search' => "users#search"

  get ':action' => 'static#:action'
end

app/views/layouts/_bootstrap_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_header.html.haml
%div

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      %button.btn.btn-navbar{:"data-toggle"=>"collapse", :"data-target"=>".nav-collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to 'Mizzou ACM', root_path, :class=>"brand"
      .nav-collapse.collapse
        %ul.nav
          =nav_link 'Events', events_path
          =nav_link 'Members', users_path
          =nav_link 'Groups', groups_path
          =nav_link 'Facebook', 'https://www.facebook.com/groups/MizzouACM/?fref=ts'
        .pull-right
          %ul.nav
            - if user_signed_in?
              %li
                = link_to current_user, {:style=> 'padding: 0px;'} do
                  %img{:src=>current_user.gravatar_url, :id=>'nav-gravatar'}
              %li.dropdown
                %a.dropdown-toggle{:href=>"#", :"data-toggle"=>"dropdown"}
                  =current_user.name
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "My Profile", current_user
                  - if user_is_admin?
                    %li=link_to 'New Post', new_post_path
                  %li.divider
                  %li= link_to 'Logout', signout_path
            - else
              = link_to 'Sign in with GitHub', signin_path, :class=>"btn btn-teal"

app/views/layouts/_navigation.html.haml
= link_to "Mizzouacm", root_path, :class => 'brand'
%ul.nav
  %li
    = link_to 'Events', events_path
  - if user_signed_in?

    %li
      = link_to 'Logout', signout_path
    %li.pull-right
      = link_to "Logged in as #{current_user.name}", edit_user_path(current_user)
  - else
    %li
      = link_to 'Login', signin_path

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Mizzouacm"
      %meta{:content => content_for?(:description) ? yield(:description) : "Mizzouacm", :name => "description"}
        = stylesheet_link_tag "bootstrap_and_overrides", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/bootstrap_messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Mizzou ACM
    = javascript_include_tag "application", :media => "all"
    = stylesheet_link_tag "application", :media => "all"
    = csrf_meta_tag
    %link{:href=>"http://fonts.googleapis.com/css?family=Open+Sans", :rel=>'stylesheet'}
    %meta{:name=>"viewport", :content=>"width=device-width, initial-scale=1.0"}
  %body{:style=>"background: url('/assets/backgrounds/6.jpg') no-repeat center center fixed"}
    = render 'layouts/nav'
    .container
      #main{:role => "main"}
        = render 'layouts/messages'
        = yield